### ISSUE TITLE
Jetstream validation should require all defined segments to be calculated

### ISSUE THREAD

**Issue by danielkberry** [mozilla/metric-hub#1124]
Currently, it's possible to define a segment in a custom config via the `segments.segment_name` syntax but then not specify that segment to be computed. The list of segments to be computed is specified under the experiments section. This means that users can believe they're defining a segment, but then be confused when that segment is not calculated. 

For example, this config: 
```toml
[segments]
[segments.my_segment]
select_expression = '...'
```

should fail validation, while this config:

```toml
[experiment]
segments = ['my_segment']

[segments]
[segments.my_segment]
select_expression = '...'
```

should pass

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CIRRUS-863)
