### ISSUE TITLE
Ability to suppress metric display in Experimenter

### ISSUE THREAD

**Issue by danielkberry** [mozilla/metric-hub#415]
Some metrics may only be defined for a single branch. These can be confusing when displayed in Experimenter. It would be nice to have the ability to suppress metric display in Experimenter as configured through metric-hub. For example: 

```toml
[metrics.my_metric]
suppress_experimenter_display = true
```
