### ISSUE TITLE
Ensure outcome metrics properly override

### ISSUE THREAD

**Issue by mikewilli** [mozilla/metric-hub#933]
We had a problem where jetstream was reporting errors with `urlbar_impressions` not having a statistic defined despite a statistic configured in the outcome definition, affecting only experiments with the Firefox Suggest outcome. This occurred following the addition of a top-level metric with the same name, which appeared to affect the outcome metric's definition, which I believe should have overridden the top-level definition. 

The metric in `definitions/firefox_desktop.toml`
```toml
[metrics.urlbar_impressions]
select_expression = "COALESCE(COUNTIF(is_terminal), 0)"
data_source = "urlbar_events"
friendly_name = "URL Bar Impressions"
```

and in `jetstream/outcomes/firefox_desktop/firefox_suggest.toml`
```toml
[metrics.urlbar_impressions]
select_expression = "COUNTIF(is_terminal)"
data_source = "urlbar_events"
description = "The number of times a user exits the urlbar dropdown menu, either by abandoning the urlbar, engaging with a urlbar result, or selecting an annoyance signal that closes the urlbar dropdown menu"
friendly_name = "Urlbar search sessions"
exposure_basis = ["exposures", "enrollments"]
statistics = { deciles = {}, bootstrap_mean = {} }
```

We should ensure that metric definitions in outcomes override top-level metric definitions as expected.
